apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "osu-server-spectator-chart.fullname" . }}
  labels:
    {{- include "osu-server-spectator-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "osu-server-spectator-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "osu-server-spectator-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "osu-server-spectator-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: oauth-public-key-secret
          secret:
            {{- if .Values.useSharedSecretsFromOsuWebChart }}
            secretName: {{ include "osu-web-chart.fullname" . }}-shared-oauth-public-key
            {{- else }}
            secretName: {{ include "osu-server-spectator-chart.fullname" . }}-oauth-public-key
            {{- end }}
            items:
              - key: oauth-public.key
                path: oauth-public.key
      {{- with .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ toYaml . }}
      {{- end }}
      {{- if .Values.hostNetwork }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.internalPort }}
              # hostPort is automatically set by Kubernetes when using hostNetwork, but is not automatically unset when turning it off.
              # This causes the pod to fail to start if it is restarted without hostNetwork.
              # Setting hostPort to 0 when not using hostNetwork fixes this.
              {{- if .Values.hostNetwork }}
              hostPort: {{ .Values.service.internalPort }}
              {{- else }}
              hostPort: 0
              {{- end }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /app/oauth-public.key
              name: oauth-public-key-secret
              subPath: oauth-public.key
              readOnly: true
          env:
            - name: SERVER_PORT
              value: "{{ .Values.service.internalPort }}"
            - name: SENTRY_DSN
              value: "{{ .Values.config.spectatorServer.sentry.url }}"
            - name: SENTRY_ENVIRONMENT
              value: "{{ .Values.config.spectatorServer.sentry.environment }}"
            {{- with .Values.config.laravel.legacy.sharedInteropDomain }}
            - name: SHARED_IO_DOMAIN
              value: {{ . | quote }}
            # old name (was replaced as of 20250213)
            - name: LEGACY_IO_DOMAIN
              value: {{ . | quote }}
            {{- end }}
            {{- range .Values.extraEnv }}
            - {{- toYaml . | nindent 14 }}
            {{- end }}
          envFrom:
            - secretRef:
                {{- if .Values.useSharedSecretsFromOsuWebChart }}
                name: {{ include "osu-web-chart.fullname" . }}-shared
                {{- else }}
                name: {{ include "osu-server-spectator-chart.fullname" . }}
                {{- end }}
                optional: false
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
