{{- if not .Values.useSharedSecretsFromOsuWebChart }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "osu-server-spectator-chart.fullname" . }}
  labels:
    {{- include "osu-server-spectator-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.config.spectatorServer.env }}
  ASPNETCORE_ENVIRONMENT: "{{ .Values.config.spectatorServer.env }}"
  {{- end }}
  DB_HOST: {{ required "Missing db host" .Values.config.db.host }}
  {{- if .Values.config.db.username }}
  DB_USER: {{ .Values.config.db.username }}
  {{- end }}
  {{- if .Values.config.db.port }}
  DB_PORT: {{ .Values.config.db.port }}
  {{- end }}
  REDIS_HOST: {{ required "Missing redis host" .Values.config.redis.host | quote }}

  {{- if .Values.config.laravel.legacy.sharedInteropSecret }}
  SHARED_INTEROP_SECRET: {{ .Values.config.laravel.legacy.sharedInteropSecret | b64enc | quote }}
  {{- end }}
{{- end }}
