apiVersion: v2
name: osu-web
description: production osu-web deployment in Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 2024.201.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "2024.201.0"

dependencies:
  - name: osu-beatmap-difficulty-lookup-cache
    version: 2023.905.0
    repository: https://ppy.github.io/helm-charts
    condition: osu-beatmap-difficulty-lookup-cache.enabled
  - name: osu-notification-server
    version: 2023.905.0
    repository: https://ppy.github.io/helm-charts
    condition: osu-notification-server.enabled
  - name: osu-server-spectator
    version: 2023.905.0
    repository: https://ppy.github.io/helm-charts
    condition: osu-server-spectator.enabled
  - name: osu-elastic-indexer
    version: 2023.823.0
    repository: https://ppy.github.io/helm-charts
    condition: osu-elastic-indexer.enabled
  - name: osu-queue-score-statistics
    version: 2023.823.0
    repository: https://ppy.github.io/helm-charts
    condition: osu-queue-score-statistics.enabled
  - name: scthumber
    version: 2023.316.0
    repository: https://ppy.github.io/helm-charts
    condition: scthumber.enabled
  - name: mysql
    version: 8.5.6
    repository: https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami
    condition: mysql.enabled
  - name: redis
    version: 14.1.0
    repository: https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami
    condition: redis.enabled
  - name: elasticsearch
    version: 7.16.2
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled
