{{- if not .Values.useSharedSecretsFromOsuWebChart }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "osu-server-beatmap-submission.fullname" . }}
  labels:
    {{- include "osu-server-beatmap-submission.labels" . | nindent 4 }}
type: Opaque
data:
  DB_HOST: {{ .Values.config.db.host | b64enc | quote }}
  {{- if .Values.config.db.port }}
  DB_PORT: {{ .Values.config.db.port | b64enc | quote }}
  {{- end }}
  DB_USER: {{ .Values.config.db.username | b64enc | quote }}
  DB_PASS: {{ .Values.config.db.password | b64enc | quote }}
  DB_NAME: {{ .Values.config.db.database | b64enc | quote }}
  {{- if .Values.config.laravel.legacy.sharedInteropSecret }}
  SHARED_INTEROP_SECRET: {{ .Values.config.laravel.legacy.sharedInteropSecret | b64enc | quote }}
  {{- end }}

  BEATMAP_STORAGE_TYPE: {{ .Values.config.storage.driver | b64enc | quote }}
  {{- if eq .Values.config.storage.driver "local" }}
  LOCAL_BEATMAP_STORAGE_PATH: {{ "/storage" | b64enc | quote }}
  {{- else if eq .Values.config.storage.driver "s3" }}
  S3_ACCESS_KEY: {{ .Values.config.storage.s3.key | b64enc | quote }}
  S3_SECRET_KEY: {{ .Values.config.storage.s3.secret | b64enc | quote }}
  S3_CENTRAL_BUCKET_NAME: {{ .Values.config.storage.s3.centralBucketName | b64enc | quote }}
  S3_BEATMAPS_BUCKET_NAME: {{ .Values.config.storage.s3.beatmapsBucketName | b64enc | quote }}
  {{- end }}
{{- end }}
