{{- if not .Values.useSharedSecretsFromOsuWebChart }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "osu-queue-score-statistics-chart.fullname" . }}
  labels:
    {{- include "osu-queue-score-statistics-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.config.db.connectionString }}
  DB_CONNECTION_STRING: {{ .Values.config.db.connectionString | quote }}
  {{- end }}
  DB_HOST: {{ .Values.config.db.host | quote }}
  DB_USER: {{ .Values.config.db.username | quote }}
  DB_PASS: {{ .Values.config.db.password | quote }}
  DB_NAME: {{ .Values.config.db.database | quote }}
  REDIS_HOST: {{ required "Missing redis host" .Values.config.redis.host | quote }}
{{- end }}
