apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "osu-beatmap-difficulty-lookup-cache-chart.fullname" . }}
  labels:
    {{- include "osu-beatmap-difficulty-lookup-cache-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "osu-beatmap-difficulty-lookup-cache-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "osu-beatmap-difficulty-lookup-cache-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "osu-beatmap-difficulty-lookup-cache-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if and .Values.useSharedSecretsFromOsuWebChart .Values.config.beatmapDifficultyLookupCache.useDatabaseLookups }}
          env:
            - name: USE_DATABASE_LOOKUPS
              value: "true"
          {{- end }}
          envFrom:
            - secretRef:
                {{- if .Values.useSharedSecretsFromOsuWebChart }}
                name: {{ include "osu-web-chart.fullname" . }}-shared
                {{- else }}
                name: {{ include "osu-beatmap-difficulty-lookup-cache-chart.fullname" . }}
                {{- end }}
                optional: false
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
