{{- if .Values.config.laravel.schedule.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "osu-web-chart.fullname" . }}-schedule
  labels:
    {{- include "osu-web-chart.labels" (dict "root" . "options" (dict "component" "schedule")) | nindent 4 }}
spec:
  schedule: {{ .Values.config.laravel.schedule.cron | quote }}
  concurrencyPolicy: {{ .Values.config.laravel.schedule.concurrencyPolicy | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          affinity:
            podAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      {{- include "osu-web-chart.selectorLabels" (dict "root" . "options" (dict "component" "octane")) | nindent 22 }}
                  topologyKey: kubernetes.io/hostname
                weight: 50
          restartPolicy: OnFailure
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "osu-web-chart.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
            - name: {{ .Chart.Name }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
                - /app/artisan
                - schedule:run
                {{- range .Values.config.laravel.schedule.additionalOptions }}
                - {{ . }}
                {{- end }}
              resources:
                {{- toYaml (.Values.config.laravel.schedule.resources | default .Values.config.laravel.octane.resources) | nindent 16 }}
              volumeMounts:
                - mountPath: /app/storage/oauth-public.key
                  name: secret-shared-oauth-public-key
                  subPath: oauth-public.key
                  readOnly: true
                - mountPath: /app/storage/oauth-private.key
                  name: secret-oauth-private-key
                  subPath: oauth-private.key
                  readOnly: true
              env:
                - name: DATADOG_STATSD_HOST
                  valueFrom:
                    fieldRef:
                      fieldPath: status.hostIP
              envFrom:
                - secretRef:
                    name: {{ include "osu-web-chart.fullname" . }}-env
          volumes:
            - name: secret-shared-oauth-public-key
              secret:
                secretName: {{ include "osu-web-chart.fullname" . }}-shared-oauth-public-key
            - name: secret-oauth-private-key
              secret:
                secretName: {{ include "osu-web-chart.fullname" . }}-oauth-private-key
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end -}}
