{{- if eq "local" .Values.config.storage.driver }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "osu-web-chart.fullname" $ }}
  labels:
    helm.sh/resource-policy: "keep"
    {{- include "osu-web-chart.labels" (dict "root" . "options" (dict)) | nindent 4 }}
spec:
  volumeMode: Filesystem
  {{- with .Values.config.storage.local.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  {{- with .Values.config.storage.local.volumeName }}
  volumeName: {{ . }}
  {{- end }}
  accessModes:
    {{- range .Values.config.storage.local.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.config.storage.local.size | quote }}
{{- end }}
