apiVersion: v1
kind: Secret
metadata:
  name: {{ include "osu-web-chart.fullname" . }}-shared
  labels:
    {{- include "osu-web-chart.labels" (dict "root" . "options" (dict)) | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.config.laravel.debug }}
  APP_DEBUG: "{{ .Values.config.laravel.debug }}"
  {{- end }}
  APP_ENV: {{ required "Missing app env" .Values.config.laravel.env }}
  {{- if .Values.config.spectatorServer.env }}
  ASPNETCORE_ENVIRONMENT: "{{ .Values.config.spectatorServer.env }}"
  {{- end }}
  DB_DATABASE: {{ .Values.config.db.database | quote }}
  DB_HOST: {{ include "osu-web.databaseHost" . | quote }}
  {{- if .Values.config.db.password }}
  DB_PASSWORD: {{ .Values.config.db.password | quote }}
  {{- end }}
  DB_USER: {{ .Values.config.db.username | quote }}
  DB_USERNAME: {{ .Values.config.db.username | quote }}
  {{- if .Values.config.dbName.chat }}
  DB_NAME_CHAT: {{ .Values.config.dbName.chat }}
  {{- end }}
  ES_HOST: {{ include "osu-web.elasticsearchHost" . | quote }}
  ES_HOST_URI: http://{{ include "osu-web.elasticsearchHost" . }}:9200
  {{- if not (eq nil .Values.config.elasticsearch.indexPrefix) }}
  ES_INDEX_PREFIX: {{ .Values.config.elasticsearch.indexPrefix | quote }}
  {{- end }}
  APP_KEY: "{{ required "Missing Laravel appKey" .Values.config.laravel.appKey }}"
  REDIS_HOST: {{ include "osu-web.redisAppHost" . }}
  REDIS_PORT: {{ .Values.config.redis.app.port | quote }}
  NOTIFICATION_REDIS_HOST: {{ include "osu-web.redisNotificationHost" . }}
  NOTIFICATION_REDIS_PORT: {{ .Values.config.redis.notification.port | quote }}
  {{- if .Values.config.laravel.session.prefix }}
  SESSION_PREFIX: "{{ .Values.config.laravel.session.prefix }}"
  {{- end }}
  CLIENT_CHECK_VERSION: {{ .Values.config.clientCheckVersion | int | quote }}
  LEGACY_IO_DOMAIN: "http://{{ include "osu-web-chart.fullname" . }}:{{ .Values.service.port }}"
