apiVersion: v1
kind: Service
metadata:
  name: {{ include "osu-web-chart.fullname" . }}-assets
  labels:
    {{- include "osu-web-chart.labels" (dict "root" . "options" (dict "component" "assets")) | nindent 4 }}
  {{- with .Values.assets.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.assets.service.type }}
  ports:
    - port: {{ .Values.assets.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "osu-web-chart.selectorLabels" (dict "root" . "options" (dict "component" "assets")) | nindent 4 }}
