{{- if and .Values.config.upgradeJob.enabled (or (and .Values.config.upgradeJob.insertOsuWebBuild.enabled (not .Release.IsInstall)) .Values.config.upgradeJob.migrate) -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "osu-web-chart.fullname" . }}-upgrade
  labels:
    {{- include "osu-web-chart.labels" (dict "root" . "options" (dict "component" "upgrade")) | nindent 4 }}
    tier: upgrade
  annotations:
    "helm.sh/hook": post-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 0
  template:
    {{- with .Values.config.upgradeJob.podAnnotations }}
    metadata:
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "osu-web-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            {{ $commands := list }}
            {{- if and .Values.config.upgradeJob.insertOsuWebBuild.enabled (not .Release.IsInstall) -}}
            {{- $commands = append $commands (printf "%s%s" "/app/artisan builds:create --stream-id=" (toString .Values.config.upgradeJob.insertOsuWebBuild.streamId)) -}}
            {{- end -}}
            {{- if .Values.config.upgradeJob.migrate -}}
            {{- $commands = append $commands "/app/artisan migrate --force" -}}
            {{- end -}}
            - /bin/sh
            - -c
            - {{ join " && " $commands }}
          resources:
            {{- toYaml (.Values.config.upgradeJob.resources | default .Values.resources) | nindent 12 }}
          volumeMounts:
            - mountPath: /app/storage/oauth-public.key
              name: secret-shared-oauth-public-key
              subPath: oauth-public.key
              readOnly: true
            - mountPath: /app/storage/oauth-private.key
              name: secret-oauth-private-key
              subPath: oauth-private.key
              readOnly: true
          env:
            - name: DATADOG_STATSD_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_ENTITY_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
          envFrom:
            - secretRef:
                name: {{ include "osu-web-chart.fullname" . }}-env-upgrade
      volumes:
        - name: secret-shared-oauth-public-key
          secret:
            secretName: {{ include "osu-web-chart.fullname" . }}-shared-oauth-public-key-upgrade
        - name: secret-oauth-private-key
          secret:
            secretName: {{ include "osu-web-chart.fullname" . }}-oauth-private-key-upgrade
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
