{{- if not .Values.useSharedSecretsFromOsuWebChart }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "osu-notification-server-chart.fullname" . }}
  labels:
    {{- include "osu-notification-server-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.config.notificationServer.debug }}
  APP_DEBUG: "{{ .Values.config.notificationServer.debug }}"
  {{- end }}
  APP_ENV: {{ required "Missing app env" .Values.config.notificationServer.env }}
  {{- if .Values.config.db.database }}
  DB_DATABASE: {{ .Values.config.db.database }}
  {{- end }}
  DB_HOST: {{ required "Missing db host" .Values.config.db.host }}
  {{- if .Values.config.db.password }}
  DB_PASSWORD: {{ .Values.config.db.password }}
  {{- end }}
  {{- if .Values.config.db.username }}
  DB_USERNAME: {{ .Values.config.db.username }}
  {{- end }}
  {{- if .Values.config.dbName.chat }}
  DB_NAME_CHAT: {{ .Values.config.dbName.chat }}
  {{- end }}
  APP_KEY: "{{ required "Missing Laravel appKey" .Values.config.laravel.appKey }}"
  REDIS_HOST: {{ required "Missing redis host" .Values.config.redis.app.host }}
  {{- if .Values.config.redis.app.port }}
  REDIS_PORT: "{{ .Values.config.redis.app.port }}"
  {{- end }}
  NOTIFICATION_REDIS_HOST: {{ required "Missing redis notification host" .Values.config.redis.notification.host }}
  {{- if .Values.config.redis.notification.port }}
  NOTIFICATION_REDIS_PORT: "{{ .Values.config.redis.notification.port }}"
  {{- end }}
  {{- if .Values.config.laravel.session.prefix }}
  SESSION_PREFIX: "{{ .Values.config.laravel.session.prefix }}"
  {{- end }}
{{- end }}
